# Generated by Django 5.0.6 on 2024-07-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('jpg', models.ImageField(upload_to='images/')),
                ('gif', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
