# Generated by Django 5.0.6 on 2024-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='jpg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
