# Generated by Django 4.1 on 2022-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0002_tile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='color',
            field=models.CharField(default='#000', max_length=4),
        ),
    ]
