# Generated by Django 4.1 on 2022-09-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0003_alter_tile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
