# Generated by Django 4.1 on 2022-09-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0004_tile_tile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='color',
        ),
    ]
