# Generated by Django 4.1 on 2022-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0006_alter_tile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_type',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(choices=[('L', 'Land'), ('W', 'Water')], default='L', max_length=1),
        ),
    ]
