# Generated by Django 4.1 on 2022-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0007_area_area_type_alter_tile_tile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('food', models.IntegerField()),
                ('production', models.IntegerField()),
                ('culture', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area_type', 'name']},
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('C', 'Continent'), ('I', 'Island'), ('M', 'Mountain'), ('S', 'Sea'), ('L', 'Lake'), ('R', 'River')], default='S', max_length=1),
        ),
    ]
