# Generated by Django 4.1 on 2022-09-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0008_resource_alter_area_options_alter_area_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='civilization.resource'),
        ),
    ]
