# Generated by Django 4.1 on 2022-09-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0009_tile_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='civilization.civilization'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiles', to='civilization.resource'),
        ),
    ]
