# Generated by Django 4.1 on 2022-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0010_alter_tile_owner_alter_tile_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['food', 'production', 'culture']},
        ),
        migrations.AddField(
            model_name='civilization',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
