# Generated by Django 4.1 on 2022-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilization', '0011_alter_resource_options_civilization_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilization',
            name='culture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilization',
            name='culture_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilization',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilization',
            name='food_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilization',
            name='production',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civilization',
            name='production_level',
            field=models.IntegerField(default=0),
        ),
    ]
