# Generated by Django 4.1 on 2022-08-28 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_image_author_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
