# Generated by Django 4.1 on 2022-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_author_date_author_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='upload/article_images/'),
        ),
    ]
