# Generated by Django 4.1 on 2022-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='static/upload/article_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(upload_to='static/upload/profile_images/'),
        ),
    ]
