# Generated by Django 4.1 on 2022-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_article_image_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
