# Generated by Django 4.1 on 2022-08-29 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_tag_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 23, 43, 35, 701735)),
        ),
    ]
