# Generated by Django 4.1 on 2022-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorsukUlam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borsukulampoint',
            name='direction',
            field=models.CharField(default='', max_length=2),
        ),
    ]
